'use strict';
module.exports = {
    get: () => {
        return Promise.resolve({
            data:
            {
                "term_id": 2,
                "name": "Menu",
                "slug": "menu",
                "term_group": 0,
                "term_taxonomy_id": 2,
                "taxonomy": "nav_menu",
                "description": "",
                "parent": 0,
                "count": 3,
                "filter": "raw",
                "items": [
                    {
                        "ID": 16,
                        "post_author": "1",
                        "post_date": "2019-08-29 09:19:49",
                        "post_date_gmt": "2019-08-29 09:19:49",
                        "post_content": " ",
                        "post_title": "",
                        "post_excerpt": "",
                        "post_status": "publish",
                        "comment_status": "closed",
                        "ping_status": "closed",
                        "post_password": "",
                        "post_name": "16",
                        "to_ping": "",
                        "pinged": "",
                        "post_modified": "2019-09-04 08:48:48",
                        "post_modified_gmt": "2019-09-04 08:48:48",
                        "post_content_filtered": "",
                        "post_parent": 0,
                        "guid": "https://infavormarketing.nl/wordpress/?p=16",
                        "menu_order": 1,
                        "post_type": "nav_menu_item",
                        "post_mime_type": "",
                        "comment_count": "0",
                        "filter": "raw",
                        "db_id": 16,
                        "menu_item_parent": "0",
                        "object_id": "5",
                        "object": "page",
                        "type": "post_type",
                        "type_label": "Pagina",
                        "url": "https://infavormarketing.nl/wordpress/",
                        "title": "Home",
                        "target": "",
                        "attr_title": "",
                        "description": "",
                        "classes": [
                            ""
                        ],
                        "xfn": ""
                    },
                    {
                        "ID": 15,
                        "post_author": "1",
                        "post_date": "2019-08-29 09:19:49",
                        "post_date_gmt": "2019-08-29 09:19:49",
                        "post_content": " ",
                        "post_title": "",
                        "post_excerpt": "",
                        "post_status": "publish",
                        "comment_status": "closed",
                        "ping_status": "closed",
                        "post_password": "",
                        "post_name": "15",
                        "to_ping": "",
                        "pinged": "",
                        "post_modified": "2019-09-04 08:48:48",
                        "post_modified_gmt": "2019-09-04 08:48:48",
                        "post_content_filtered": "",
                        "post_parent": 0,
                        "guid": "https://infavormarketing.nl/wordpress/?p=15",
                        "menu_order": 2,
                        "post_type": "nav_menu_item",
                        "post_mime_type": "",
                        "comment_count": "0",
                        "filter": "raw",
                        "db_id": 15,
                        "menu_item_parent": "0",
                        "object_id": "7",
                        "object": "page",
                        "type": "post_type",
                        "type_label": "Pagina",
                        "url": "https://infavormarketing.nl/wordpress/over-ons/",
                        "title": "Over ons",
                        "target": "",
                        "attr_title": "",
                        "description": "",
                        "classes": [
                            ""
                        ],
                        "xfn": ""
                    },
                    {
                        "ID": 14,
                        "post_author": "1",
                        "post_date": "2019-08-29 09:19:49",
                        "post_date_gmt": "2019-08-29 09:19:49",
                        "post_content": " ",
                        "post_title": "",
                        "post_excerpt": "",
                        "post_status": "publish",
                        "comment_status": "closed",
                        "ping_status": "closed",
                        "post_password": "",
                        "post_name": "14",
                        "to_ping": "",
                        "pinged": "",
                        "post_modified": "2019-09-04 08:48:48",
                        "post_modified_gmt": "2019-09-04 08:48:48",
                        "post_content_filtered": "",
                        "post_parent": 0,
                        "guid": "https://infavormarketing.nl/wordpress/?p=14",
                        "menu_order": 3,
                        "post_type": "nav_menu_item",
                        "post_mime_type": "",
                        "comment_count": "0",
                        "filter": "raw",
                        "db_id": 14,
                        "menu_item_parent": "0",
                        "object_id": "10",
                        "object": "page",
                        "type": "post_type",
                        "type_label": "Pagina",
                        "url": "https://infavormarketing.nl/wordpress/contact/",
                        "title": "Contact",
                        "target": "",
                        "attr_title": "",
                        "description": "",
                        "classes": [
                            ""
                        ],
                        "xfn": ""
                    }
                ]
            }
        });
    }
};